# Generated by Django 4.1.2 on 2022-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('type_news', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('article', models.TextField()),
                ('img_article_url', models.CharField(max_length=255)),
                ('title_url', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('author_link', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
            ],
        ),
    ]
