# Generated by Django 4.1.2 on 2022-10-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='author_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_article_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
