# Generated by Django 4.1.2 on 2022-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_article_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
